### ISSUE TITLE
Can you provide the 'Australia_Polygon'？

### ISSUE THREAD

**Issue by lsq210** [sulova/AustraliaFires#1]
I'm very interested in your research. When I ran the code, I found that it needed Australian's States shp. I tried to use the my data but it didn't work. Can you provide it or tell me how to get it? Thank you very much!
```
//______Import SHP Australian's States__________________________________________
var Australia_shp = ee.FeatureCollection("users/sulovaandrea/Australia_Polygon");

```

**Comment by sulova** [comment]
Hi, 
its available now!
